services:
  postgres:
    image: postgres:15
    container_name: raizefund-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raize_fund_db
    ports:
      - "5462:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
